// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9iU0W6w_tVD0Mdo2fWcNm00vZE-Ujf2o',
    appId: '1:706735512676:web:c0de6e89564babf3039371',
    messagingSenderId: '706735512676',
    projectId: 'appforus-7ce83',
    authDomain: 'appforus-7ce83.firebaseapp.com',
    storageBucket: 'appforus-7ce83.appspot.com',
    measurementId: 'G-ZC7MPQ253X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpMaVIZrv1W93f6qKY9zWrLF4I0k7qCRg',
    appId: '1:706735512676:android:a55e7170b5e79a38039371',
    messagingSenderId: '706735512676',
    projectId: 'appforus-7ce83',
    storageBucket: 'appforus-7ce83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHbI6T4KxH_RBRR2EwoXKoyju11Wiv6hs',
    appId: '1:706735512676:ios:421943e7ecb53274039371',
    messagingSenderId: '706735512676',
    projectId: 'appforus-7ce83',
    storageBucket: 'appforus-7ce83.appspot.com',
    iosBundleId: 'com.example.appForUs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHbI6T4KxH_RBRR2EwoXKoyju11Wiv6hs',
    appId: '1:706735512676:ios:c112d495d8a17ad1039371',
    messagingSenderId: '706735512676',
    projectId: 'appforus-7ce83',
    storageBucket: 'appforus-7ce83.appspot.com',
    iosBundleId: 'com.example.appForUs.RunnerTests',
  );
}
